---
title: "Q7_GAss"
author: "Oghosa"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(haven) 
library(readr) 
library(dplyr) 
pacman::p_load(haven, readr, dplyr, tidyverse, table1, DiagrammeR, rsvg)
```

```{r}
class_SA_csv <-
 read_csv(
   "https://github.com/kijohnson/ADA-2024/raw/main/Class%201%20(Getting%20started%20and%20RR%20I)/Lab/Class%201%20Survey%20Fall%202024_di.csv"
   )
```

```{r}
names(class_SA_csv)[1:27] <- c("ID", "cats", "dogs", "item", "slogan", "day", "LOH", "food", "drink", "season", "month", "hobby", "degree", "specialization", "software", "Rx", "coding", "duration", "learn", "interest", "number", "bday", "bmonth", "country", "state", "city", "LOE")

colnames(class_SA_csv)
```

```{r}
unique(class_SA_csv$LOH)
```

```{r}
class_SA_csv1 <- class_SA_csv %>%
  filter(LOH=="Owl (I am a night person)") 

ex1 <- nrow(class_SA_csv)- nrow(class_SA_csv1)
ex1
```

```{r}
class_SA_csv1$bmonth <- as.numeric(class_SA_csv1$bmonth)

class_SA_csv2 <- class_SA_csv1 %>%
  drop_na(bmonth) 

ex2 <- nrow(class_SA_csv1) - nrow(class_SA_csv2)
ex2
```
```{r}
table(class_SA_csv2$coding)
```

```{r}
class_SA_csv3 <- class_SA_csv2 %>%
  filter(coding <=3)

ex3 <- nrow(class_SA_csv2) - nrow(class_SA_csv3)
ex3
```
```{r}
grViz(diagram = "digraph flowchart{ # gives beginning of flowchart

      # node definitions with substituted label text
      
      node [fontname = Helvetica, shape = rectangle, fontsize=10] 
      
      # Define the nodes: nodes indicate how many boxes you will have in your diagram. Since I have three sets of exclusions, I will have four nodes.
      
      node1 [label = '@@1'] # starting number
      node2 [label = '@@2'] # number after exclusion 1
      node3 [label = '@@3'] # number after exclusion 2
      node4 [label = '@@4'] # number after exclusion 3
      
      # edge definitions with the node IDs are used to indicate how the rectangle boxes flow from each other. 
      
      node1 -> node2 -> node3 -> node4
}
      # This set of code provides the text in each rectangle box.
      [1]: 'Records received from KJ_Github n = 29'
      [2]: 'Excluding 18 individuals who are not night folks n = 11'
      [3]: 'Excluding 1 individual with missing birth month data \\n (or entered a non-numeric figure) n = 10'
      [4]: 'Excluding 2 individuals who have greater than 3 \\n coding comfort level (very advanced) n = 8'
      ")
```

```{r}
table1(~ cats + dogs + day + season + month + degree + software + Rx + coding + duration + number + country + LOE, class_SA_csv3)
```

```{r}
table1(~ cats + dogs + day + season + month + degree + specialization + software + Rx + coding + duration + number + country | specialization, class_SA_csv3)
```

